apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spinnaker-spike
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spinnaker-spike
    spec:
      containers:
      - name: app
        image: alecjacobs/spinnaker-spike
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    app: minio
